# Generated by Django 6.0.2 on 2026-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='delayed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_level',
            field=models.CharField(default='low', max_length=20),
        ),
    ]
